version: "3"
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    command: '-u "user1;pass1" -u "user2;pass2" -s "media;/media;yes;no" -p'
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    volumes:
      - /mnt/storage:/media
