version: "3"
services:
  samba:
    image: dperson/samba
    container_name: samba
    env_file:
      - .env
    restart: always
    command: '-u "${USER1};${PASS1}" -u "${USER2};${PASS2}" -s "media;/media;yes;no" -p'
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    volumes:
      - /mnt/storage:/media
