version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - .env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    restart: always
    environment:
      TZ: 'America/Montevideo'
      WEBPASSWORD: ${PASSWORD}
    volumes:
      - '${STORAGE}/pi-hole/etc-pihole/:/etc/pihole/'
      - '${STORAGE}/pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped