version: '2'
services:
  plex:
    image: jaymoulin/plex
    container_name: plex
    env_file:
      - .env
    expose:
      - 32400
      - 33400
    volumes:
      - ${STORAGE}/plex/config:/root/Library
      - ${MEDIA}:/media
    restart: always
    network_mode: "host"
