version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    env_file:
      - .env
    ports:
      - 1234:80
    volumes:
      - ${STORAGE}/owncloud/media/:/var/www/html
      - ${STORAGE}/owncloud/apps:/var/www/html/apps
      - ${STORAGE}/owncloud/config:/var/www/html/config
      - ${STORAGE}/owncloud/data:/var/www/html/data
    environment:
      TZ: 'America/Montevideo'

  # db:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example