version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 1234:80
    volumes:
      - ${STORAGE}/owncloud:/media/owncloud_data:/var/www/html
      - ${STORAGE}/owncloud/apps:/var/www/html/apps
      - ${STORAGE}/owncloud/config:/var/www/html/config
      - ${STORAGE}/owncloud/data:/var/www/html/data

  # db:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example